spring:
  application:
    name: store
  datasource:
    url: jdbc:mysql://localhost:3306/store_api?createDatabaseIfNotExist=true
    username: root
    password: '@Khashi51000'
  jpa:
    show-sql: true

logging:
  level:
    root: debug